### ISSUE TITLE
Setting up Heroku Server documentation

### ISSUE THREAD

**Issue by andrewdavisdev** [dmhacker/dmhacker-youtube#1]
Hey @dmhacker , I am pretty interested in setting up my own Heroku server so I can have AWS Lambda query my own Heroku server instead, and I have put my own Heroku URL as an Environment variable in the node.js code that I uploaded to Lambda, (replaced 'https://dmhacker-youtube.herokuapp.com' with `process.env.HEROKU_APP_URL + '/alexa/' and process.env.HEROKU_APP_URL + '/alexa+check/'`,), but what enviornment variables do I need to set on the Heroku side and what node.js Build Pack should I be targeting? Right away I am getting some error messages with this repo on Heroku and I suspect I am missing some Env Vars on the Heroku side or other configuration. Also what setup do I have to do with an AWS Bucket? Thanks

**Comment by dmhacker** [comment]
@andrewdavisdev I'll write a README with some setup instructions right away!

**Comment by dmhacker** [comment]
Whoops, didn't mean to close it just yet.

**Comment by andrewdavisdev** [comment]
@dmhacker Thanks! Looking forward to it.

**Comment by dmhacker** [comment]
See the updated README :)

**Comment by andrewdavisdev** [comment]
@dmhacker Thanks!
