### ISSUE TITLE
Keywords not found?

### ISSUE THREAD

**Issue by famewolf** [dmhacker/dmhacker-youtube#12]
Did something change on alexa?   I have both the youtube and the google developer skills setup and they worked fine for a long time..now neither seem to work...I've updated github and heroku to ensure they are deployed with the latest code but still alexa doesn't understand when I say "alexa tell youtube to play human league" which previously worked unless I'm getting the skills mixed up.

**Comment by dmhacker** [comment]
Try following the setup guide again? It works perfectly fine on my Echo Dot. I'm going to close this issue for now, and if you are still experiencing error(s), I would invite you to browse or post [here](https://github.com/dmhacker/alexa-youtube-skill/issues).
