### ISSUE TITLE
"An error occured during processing."

### ISSUE THREAD

**Issue by FitzWM** [dmhacker/dmhacker-youtube#9]
Hi,

I'm trying to set up your Alexa skill and my own Heroku server to power it, but I've run into a bit of a snag. Simply put, I believe I have the skill and Lambda set up correctly (This is my first go-around, though, so I might be mistaken about that.) yet the skill does nothing. After triple-checking the settings, I decided to go to your server and try playing a video manually, to make sure the problem wasn't on the backend. When I did, either by putting in a video ID or by searching, it only went to the video player screen, searched for about 30s, and returned me to the landing page with the message, "An error occured during processing." I then tried setting up my own Heroku server, again following your instructions, and I got the same errors on my end.

I'm really excited to get this working, and I'm sure I've just made a mistake somewhere, but I can't find it. Any thoughts?

**Comment by itsjoshpark** [comment]
The first step I did to try to resolve this issue was to update all the packages in the `package.json` file.
Doing that and deploying the updated master branch to Heroku seems to have solved the issue.

You can check for the latest versions of the dependencies by running `npm outdated`.
